name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Container
      run: |
        docker build -f Dockerfile.cpu -t entrelia/vllm-cpu:latest --shm-size=4g .