name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-cpu:
    runs-on: ubuntu-latest

    env:
      REGISTRY: us-east1-docker.pkg.dev/entrelia-prod/entrelia

    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
    - name: Docker Auth
      run: gcloud auth configure-docker us-east1-docker.pkg.dev
    - name: Build Docker Container
      run: |
        docker build -f Dockerfile.cpu -t ${{ env.REGISTRY }}/vllm-cpu:${{ github.sha }} --shm-size=4g .
    - name: Push Docker Container
      run: |
        docker push ${{ env.REGISTRY }}/vllm-cpu:${{ github.sha }}